#!/bin/bash
pwd
echo "#####################"
ls -al
echo "#####################"
cd /app
#####ORI#####./proxy http -p :$PORT -t ws --local-ws-password pass
./proxy http -p :$PORT -t ws --local-ws-password "snail007_goproxy"
